### ISSUE TITLE
[BUG] Image mal affiché sur firefox 

### ISSUE THREAD

**Issue by beligatclement** [beligatclement/hogwartslegacymap#20]
![image](https://user-images.githubusercontent.com/19620479/195582314-a409202b-546a-44ae-8975-d2336436240b.png)

Faire fonctionner ce code également sur firefox :
```css
.decoration {
	width: -webkit-fill-available;
}
```

Solution potentiel : 
```css
elem {
    width: 100%;
    width: -moz-available;          /* WebKit-based browsers will ignore this. */
    width: -webkit-fill-available;  /* Mozilla-based browsers will ignore this. */
    width: fill-available;
}
```
cf: https://stackoverflow.com/questions/26275982/putting-moz-available-and-webkit-fill-available-in-one-width-css-property
